server:
  port: 9411
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
      url: jdbc:mysql://localhost:3306/zipkin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
      username: root
      password: 12345678
      driverClassName: com.mysql.cj.jdbc.Driver
zipkin:
  storage:
    type: mysql