server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    bus:
      trace:
        enabled: false
    config:
      server:
        git:
          searchPaths: / #配置仓库路径
          username: khaojie #访问git仓库的用户名
          password: jhjkhaojie156@ #访问git仓库的用户密码
          uri: git@192.168.11.83:khaojie/springcloud-config.git
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false